VFSM.API/Models/UserViewModels/UserViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace hmx.vodafone.web.Models.UserViewModels
{
    public class UserViewModel
    {
        [Column("CREATED_DATE")]
        [Display(Name = "Created Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}")]
        public DateTime CreatedDate { get; set; }

        [Column("USER_ID")]
        [Display(Name = "Customer ID")]
        public string UserId { get; set; }

        [Column("NICK_NAME")]
        [Display(Name = "Name")]
        public string NickName { get; set; }

        [Column("MOBILE_TYPE")]
        [Display(Name = "Mobile Type")]
        public string MobileType { get; set; }

        [Column("IMEI")]
        [Display(Name = "Imei")]
        public string Imei { get; set; }

        [Column("DEVICE_COUNT")]
        [Display(Name = "Device Count")]
        public int DeviceCount { get; set; }
    }
}

VFSM.API/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using hmx.vodafone.web.Config;
using hmx.vodafone.web.Data;
using hmx.vodafone.web.Models;
using hmx.vodafone.web.Models.UserViewModels;
using hmx.vodafone.web.Models.DBModels;
using hmx.vodafone.web.Constants;
using ReflectionIT.Mvc.Paging; 
using Newtonsoft.Json;

namespace hmx.vodafone.web.Controllers
{
    [Authorize(Roles = "Admin, CS Read, CS Write")]
    public class UserController : BaseController
    {
        private HttpClient _httpClient;

        public UserController(VodafoneContext context, UserManager<ApplicationUser> userManager, IOptions<VodafoneConfig> vodafoneConfig)
        : base(context, userManager)
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri(vodafoneConfig.Value.ApiServerUrl);
            _httpClient.DefaultRequestHeaders.Accept.Clear();
            _httpClient.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));
        }

        #region Index
        [Authorize(Roles = "Admin, CS Read, CS Write")]
        public async Task<IActionResult> Index(string filter, string sortExpression = "-CreatedDate", int page = 1)
        {
            IQueryable<UserViewModel> qry = null;

            if (string.IsNullOrEmpty(filter)) 
            {
                qry = from u in _context.VodafoneUsers
                      select new UserViewModel 
                      { 
                          CreatedDate = u.CreatedDate,
                          UserId = u.UserId,
                          NickName = u.NickName,
                          MobileType = u.MobileType,
                          Imei = _context.VodafeonDevices.Where(d => d.DeviceId == _context.VodafoneUserDevices.Where(x => x.UserId == u.UserId).FirstOrDefault().DeviceId).FirstOrDefault().DeviceUid,
                          DeviceCount = _context.VodafoneUserDevices.Where(x => x.UserId == u.UserId).Count() 
                      };
            } 
            else 
            {
                qry = from d in _context.VodafeonDevices
                      join ud in _context.VodafoneUserDevices on d.DeviceId equals ud.DeviceId
                      join u in _context.VodafoneUsers on ud.UserId equals u.UserId
                      where d.DeviceUid == filter
                      select new UserViewModel 
                      {
                          CreatedDate = u.CreatedDate,
                          UserId = u.UserId,
                          NickName = u.NickName,
                          MobileType = u.MobileType,
                          Imei = filter,
                          DeviceCount = _context.VodafoneUserDevices.Where(x => x.UserId == u.UserId).Count() 
                      };
            }

            var model = await PagingList<UserViewModel>.CreateAsync(qry, VF_CONSTANT.PageSize, page, sortExpression, "-CreateDate");
            model.RouteValue = new RouteValueDictionary { {"filter", filter} };

            ViewData["IsCSRead"] = IsCSReadUser();
            return View(model);
        }
        #endregion
        
        #region DeviceList
        [Authorize(Roles = "Admin, CS Read, CS Write")]
        public async Task<IActionResult> DeviceList(string filter, int page = 1)
        {
            if (string.IsNullOrEmpty(filter))
            {
                return NotFound();
            }

            ViewData["userid"] = filter;
            ViewData["devicepage"] = page;
            ViewData["IsCSRead"] = IsCSReadUser();
            var model = from ud in _context.VodafoneUserDevices.Where(x => x.UserId == filter)
                      join d in _context.VodafeonDevices on ud.DeviceId equals d.DeviceId
                      select new UserDeviceViewModel 
                      {
                          CreatedDate = d.CreatedDate,
                          DeviceId = d.DeviceId,
                          DeviceUid = d.DeviceUid,
                          Name = d.Name,
                          Imei = d.DeviceUid,
                          Role = ud.Role,
                          Status = d.Status.Replace("\"", "").Replace("[", "").Replace("]", ""),
                          UserId = filter
                      };
            
            
            return PartialView("DeviceListPartial", await PaginatedList<UserDeviceViewModel>.CreateAsync(model.AsNoTracking(), page, VF_CONSTANT.PageSize));
        }
        #endregion
        
        #region ActivityList
        [Authorize(Roles = "Admin, CS Read, CS Write")]
        public async Task<IActionResult> ActivityList(string id, int page = 1)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }
            ViewData["deviceid"] = id;
            ViewData["activitypage"] = page;

            var model = _context.VodafoneActivities.Where(x => x.DeviceId == id).OrderByDescending(x=>x.CreatedDate);
            return PartialView("ActivityListPartial", await PaginatedList<VodafoneActivity>.CreateAsync(model.AsNoTracking(), page, VF_CONSTANT.PageSize));
        }
        #endregion

        #region ActivitySeriesList
        [Authorize(Roles = "Admin, CS Read, CS Write")]
        public async Task<IActionResult> ActivitySeriesList(string id, int page = 1)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }
            ViewData["activityid"] = id;
            ViewData["activitySeriespage"] = page;

            var model = _context.VodafoneActivitySeries.Where(x => x.ActId == id).OrderByDescending(x=>x.CreatedDate);
            return PartialView("ActivitySeriesListPartial", await PaginatedList<VodafoneActivitySeries>.CreateAsync(model.AsNoTracking(), page, VF_CONSTANT.PageSize));
        }
        #endregion

        #region Register
        [HttpGet]
        [Authorize(Roles = "Admin, CS Write")]
        public IActionResult Register(string userId)
        {
            var model = new DeviceRegisterViewModel { UserId = userId };
            return PartialView("RegisterPopup", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, CS Write")]
        public async Task<IActionResult> Register(DeviceRegisterViewModel model)
        {
            var result = new ResponseModel { Success = false };
            if (ModelState.IsValid)
            {
                var user = await _context.VodafoneUsers.Where(u => u.UserId == model.UserId).FirstOrDefaultAsync();
                var device = await _context.VodafeonDevices.Where(d => d.DeviceUid == model.DeviceUid).FirstOrDefaultAsync();
                
                if (device == null)
                {
                    var generatedDeviceId = System.Guid.NewGuid().ToString();
                    var savedDevice = await _context.VodafeonDevices.AddAsync(new VodafoneDevice{
                        DeviceVersion = "0.0.0.0",
                        DeviceId = generatedDeviceId,
                        ImgUrl = string.Empty,
                        DeviceUid = model.DeviceUid,
                        Name = model.DeviceName,
                        ActivatedDate = DateTime.UtcNow,
                        Activated = true,
                        ModelId = "31-00006",
                        Status = "[\"OK\"]",
                        StatusLevel = "NORMAL",
                        CreatedDate = DateTime.UtcNow
                    });
                    await _context.SaveChangesAsync();
                    
                    await _context.VodafoneUserDevices.AddAsync(new VodafoneUserDevice{
                        UserId = model.UserId,
                        DeviceId = savedDevice.Entity.DeviceId,
                        RegName = savedDevice.Entity.Name,
                        Role = "ROOT",
                        CreatedDate = DateTime.UtcNow
                    });
                    await _context.SaveChangesAsync();
                    
                }
                else
                {
                    var userDevice = _context.VodafoneUserDevices.Where(ud => ud.DeviceId == device.DeviceId).FirstOrDefault();
                    if (userDevice != null)
                    {
                        // 등록유저가 있을 때 - UserDevice에 SUB로 등록
                        await _context.VodafoneUserDevices.AddAsync(new VodafoneUserDevice{
                            UserId = model.UserId,
                            DeviceId = device.DeviceId,
                            RegName = device.Name,
                            Role = "SUB",
                            CreatedDate = DateTime.UtcNow
                        });
                    }
                    else
                    {
                        // 등록유저가 없을 때 - UserDeivce에 ROOT로 등록
                        await _context.VodafoneUserDevices.AddAsync(new VodafoneUserDevice{
                            UserId = model.UserId,
                            DeviceId = device.DeviceId,
                            RegName = device.Name,
                            Role = "ROOT",
                            CreatedDate = DateTime.UtcNow
                        });
                    }
                    await _context.SaveChangesAsync();
                }
                result.Message = "Registration succeeded.";
                result.RedirectMethod = "refresh";
            }
            else
            {
                result.Message = "Paramater is not vaild.";
            }

VFSM.API/Views/User/ActivityListPartial.cshtml
@model hmx.vodafone.web.Models.PaginatedList<hmx.vodafone.web.Models.DBModels.VodafoneActivity>

<div class="panel panel-default">
    <div class="panel-heading" style="font-weight: bold;">
        Activity List
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                        <th>
                            Created Date
                        </th>
                        <th>
                            Activity Id
                        </th>                
                        <th>
                            Event Type
                        </th>
                        <th>
                            Battery
                        </th>
                        <th>
                            Location
                        </th>
                        <th>
                            Actions
                        </th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ActivityId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EventType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Battery)
                    </td>
                    <td>
                        Lat : @Html.DisplayFor(modelItem => item.Lat),
                        Lng : @Html.DisplayFor(modelItem => item.Lng)
                    </td>
                    <td>
                        @if (item.IsSeries) {
                            <a class="btn btn-info btn-sm" onclick="activitySeriesList('@item.ActivityId', '1');">Series History</a>
                        }
                    </td>
                </tr>
        }
            </tbody>
        </table>
        @{
            var prevActivityDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextActivityDisabled = !Model.HasNextPage ? "disabled" : "";
        }
        <a class="btn btn-light @prevActivityDisabled" onclick="activityList('@ViewData["deviceid"]', '@(Model.PageIndex - 1)');">Previous</a>
        <a class="btn btn-light @nextActivityDisabled" onclick="activityList('@ViewData["deviceid"]', '@(Model.PageIndex + 1)');">Next</a>
    </div>
</div>

VFSM.API/Views/User/ActivitySeriesListPartial.cshtml
@model hmx.vodafone.web.Models.PaginatedList<hmx.vodafone.web.Models.DBModels.VodafoneActivitySeries>

<div class="panel panel-default">
    <div class="panel-heading" style="font-weight: bold;">
        Activity History
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                        <th>
                            Created Date
                        </th>
                        <th>
                            Event Type
                        </th>
                        <th>
                            DisplayMsg
                        </th>
                        <th>
                            Location
                        </th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Action)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Message)
                    </td>
                    <td>
                        <p>Latitude : @Html.DisplayFor(modelItem => item.Lat)</p>
                        <p>Longitude : @Html.DisplayFor(modelItem => item.Lng)</p>
                    </td>
                    <td>
                    </td>
                </tr>
        }
            </tbody>
        </table>
        @{
            var prevActivitySeriesDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextActivitySeriesDisabled = !Model.HasNextPage ? "disabled" : "";
        }
        <a class="btn btn-light @prevActivitySeriesDisabled" onclick="activitySeriesList('@ViewData["activityid"]', '@(Model.PageIndex - 1)');">Previous</a>
        <a class="btn btn-light @nextActivitySeriesDisabled" onclick="activitySeriesList('@ViewData["activityid"]', '@(Model.PageIndex + 1)');">Next</a>
    </div>
</div>

VFSM.API/Views/User/DeleteUserDevicePopup.cshtml
@model hmx.vodafone.web.Models.UserViewModels.DeleteUserDeviceViewModel
  
<div>  
    <div class="modal-header">  
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>  
        <h4 class="modal-title" id="myModalLabel">Are you sure you want to delete this?</h4>  
    </div>                 
    
    <div class="modal-body">
            <form asp-controller="User" asp-action="DeleteUserDevice"
                data-ajax="true"
                data-ajax-method="POST"
                data-ajax-success="popupRegisterSuccess"
                data-ajax-failure="popupRegisterFailure">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="DeviceId" class="control-label"></label>
                    <input asp-for="DeviceId" class="form-control" disabled/>
                    <span asp-validation-for="DeviceId" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="DeviceId" />
                <div class="form-group">
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control" disabled/>
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="Page" />
                <div class="form-group">
                    <input type="submit" value="Delete" class="btn btn-danger btn-lg btn-block" />
                </div>
            </form>
    </div>
</div>  

VFSM.API/Views/User/DeviceListPartial.cshtml
@model hmx.vodafone.web.Models.PaginatedList<hmx.vodafone.web.Models.UserViewModels.UserDeviceViewModel>

@{
    bool isCSRead = (bool)ViewData["IsCSRead"];
}

<div class="panel panel-default">
    <div class="panel-heading" style="font-weight: bold;">
        Device List
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                        <th>
                            Created Date
                        </th>
                        <th>
                            Device Id
                        </th>
                        <th>
                            Name
                        </th>                
                        <th>
                            Imei
                        </th>
                        <th>
                            Role
                        </th>
                        <th>
                            Status
                        </th>
                        <th>
                            Actions
                        </th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DeviceId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Imei)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Role)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @if(isCSRead)
                        {
                            <a class="btn btn-primary btn-sm" onclick="popupSendMessage('@item.DeviceUid', '@item.UserId', '@(Model.PageIndex)');" disabled>Send</a>
                            <a class="btn btn-info btn-sm" onclick="activityList('@item.DeviceId', '1');">Activity</a>
                            <a class="btn btn-warning btn-sm" onclick="popupDeviceNameModify('@item.DeviceId', '@item.UserId', '@(Model.PageIndex)');" disabled>Modify</a>
                            <a class="btn btn-danger btn-sm" onclick="popupDeleteUserDevice('@item.DeviceId', '@item.UserId', '@(Model.PageIndex)');" disabled>Delete</a>
                        }
                        else
                        {
                            <a class="btn btn-primary btn-sm" onclick="popupSendMessage('@item.DeviceUid', '@item.UserId', '@(Model.PageIndex)');">Send</a>
                            <a class="btn btn-info btn-sm" onclick="activityList('@item.DeviceId', '1');">Activity</a>
                            <a class="btn btn-warning btn-sm" onclick="popupDeviceNameModify('@item.DeviceId', '@item.UserId', '@(Model.PageIndex)');">Modify</a>
                            <a class="btn btn-danger btn-sm" onclick="popupDeleteUserDevice('@item.DeviceId', '@item.UserId', '@(Model.PageIndex)');">Delete</a>
                        }
                    </td>
                </tr>
        }
            </tbody>
        </table>
        @{
            var prevDeviceListDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDeviceListDisabled = !Model.HasNextPage ? "disabled" : "";
        }
        <a class="btn btn-light @prevDeviceListDisabled" onclick="deviceList('@ViewData["userid"]', '@(Model.PageIndex - 1)');">Previous</a>
        <a class="btn btn-light @nextDeviceListDisabled" onclick="deviceList('@ViewData["userid"]', '@(Model.PageIndex + 1)');">Next</a>
    </div>
</div>

VFSM.API/Views/User/DeviceNameModifyPopup.cshtml
@model hmx.vodafone.web.Models.UserViewModels.DeviceNameModifyViewModel
  
<div>  
    <div class="modal-header">  
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>  
        <h4 class="modal-title" id="myModalLabel">Modify Device Name</h4>  
    </div>                 
    
    <div class="modal-body">
            <form asp-controller="User" asp-action="DeviceNameModify"
                data-ajax="true"
                data-ajax-method="POST"
                data-ajax-success="popupRegisterSuccess"
                data-ajax-failure="popupRegisterFailure">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="DeviceId" class="control-label"></label>
                    <input asp-for="DeviceId" class="form-control" disabled/>
                    <span asp-validation-for="DeviceId" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="DeviceId" />
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="Page" />
                <div class="form-group">
                    <label asp-for="DeviceUid" class="control-label"></label>
                    <input asp-for="DeviceUid" class="form-control" disabled/>
                    <span asp-validation-for="DeviceUid" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="DeviceUid" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Modify" class="btn btn-warning btn-lg btn-block" />
                </div>
            </form>
    </div>
</div>  

VFSM.API/Views/User/RegisterPopup.cshtml
@model hmx.vodafone.web.Models.UserViewModels.DeviceRegisterViewModel
  
<div>  
    <div class="modal-header">  
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>  
        <h4 class="modal-title" id="myModalLabel">Register Device</h4>  
    </div>                 
    
    <div class="modal-body">
            <form asp-controller="User" asp-action="Register"
                data-ajax="true"
                data-ajax-method="POST"
                data-ajax-success="popupRegisterSuccess"
                data-ajax-failure="popupRegisterFailure">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control" disabled/>
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="UserId" />
                <div class="form-group">
                    <label asp-for="DeviceUid" class="control-label"></label>
                    <input asp-for="DeviceUid" class="form-control" />
                    <span asp-validation-for="DeviceUid" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DeviceName" class="control-label"></label>
                    <input asp-for="DeviceName" class="form-control" />
                    <span asp-validation-for="DeviceName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Register" class="btn btn-success btn-lg btn-block" />
                </div>
            </form>
    </div>
</div>  

VFSM.API/Views/User/SendMessagePopup.cshtml
@model hmx.vodafone.web.Models.UserViewModels.SendMessageViewModel
  
<div>  
    <div class="modal-header">  
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>  
        <h4 class="modal-title" id="myModalLabel">Select Message Type</h4>  
    </div>                 
    
    <div class="modal-body">
            <form asp-controller="User" asp-action="SendMessage"
                data-ajax="true"
                data-ajax-method="POST"
                data-ajax-success="popupRegisterSuccess"
                data-ajax-failure="popupRegisterFailure">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="DeviceUid" />
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="Page" />
                <div class="form-group">
                    <label asp-for="Lat" class="control-label"></label>
                    <input type="text" value="" asp-for="Lat" class="form-control"/>
                    <span asp-validation-for="Lat" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Lng" class="control-label"></label>
                    <input type="text" value="" asp-for="Lng" class="form-control" />
                    <span asp-validation-for="Lng" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Battery" class="control-label"></label>
                    <input type="text" value="" asp-for="Battery" placeholder="0 ~ 100" class="form-control" />
                    <span asp-validation-for="Battery" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MessageType" class="control-label"></label>
                    @Html.DropDownList("MessageType", (IEnumerable<SelectListItem>)ViewData["EventTypeList"], new {@class="form-control"})
                </div>
                <div class="form-group">
                    <input type="submit" value="Send" class="btn btn-primary btn-lg btn-block" />
                </div>
            </form>
    </div>
</div>  

VFSM.API/Views/User/UserNickNameModifyPopup.cshtml
@model hmx.vodafone.web.Models.UserViewModels.UserNickNameModifyViewModel
  
<div>  
    <div class="modal-header">  
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>  
        <h4 class="modal-title" id="myModalLabel">Modify Customer Nickname</h4>  
    </div>                  
    <div class="modal-body">
            <form asp-controller="User" asp-action="UserNickNameModify"
                data-ajax="true"
                data-ajax-method="POST"
                data-ajax-success="popupRegisterSuccess"
                data-ajax-failure="popupRegisterFailure">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control" disabled/>
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="DeviceUid" />
                <div class="form-group">
                    <label asp-for="NickName" class="control-label"></label>
                    <input asp-for="NickName" class="form-control" />
                    <span asp-validation-for="NickName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Modify" class="btn btn-warning btn-lg btn-block" />
                </div>
            </form>
    </div>
</div>  